### ISSUE TITLE
gerrit do not seem to work with Ubuntu 14.04

### ISSUE THREAD

**Issue by stef277** [shanesmith/gerrit-cli#22]
After installing gerrit on Ubuntu 14.04

It seems like gerrit does not work, it simply return (or terminate) when invoke from the command line with no information

For example:

> gerrit config
>

(It doesn't prompt me for the configuration information)

**Comment by shanesmith** [comment]
Could you please include your version of Git and of Node?

**Comment by stef277** [comment]
The problem was caused by a very old version of node and npm. Updating node/npm fixed the problem.
