### ISSUE TITLE
Assigning multiple reviewers sometimes fails

### ISSUE THREAD

**Issue by simonlevasseur** [shanesmith/gerrit-cli#25]
When assigning multiple reviewers to a patch by either listing all the names or using a squad, some of the reviewers will sometimes not be assigned and a warning will be shown notifying they weren't assigned.

**Comment by shanesmith** [comment]
Thanks for reporting. =) 

This should be fixed by bc881573b6cbbc43629ae2a49e53d2e02f49215e, which will show up in the next release... which will be very soon...
